### ISSUE TITLE
Possibility to have a default setup of the overlay (floating modal?) 

### ISSUE THREAD

**Issue by ahmed1490** [magicismight/react-native-root-modal#1]
Is it possible to put the modal to have a default absolute positioned bottom value?

For eg: 
![Alt text](http://a2.mzstatic.com/eu/r30/Purple69/v4/ac/78/97/ac789734-9f73-8b9a-5a0b-5e494727a2c8/screen322x572.jpeg)

Here the more options may slide up the modal a little more to reveal more options between the button the the text.

Wondering if react-native-root-modal is the right option for something complex like this. Or something else?

**Comment by magicismight** [comment]
I`m not sure I am totally understand you.
Is this what you want?

![qq 20160222093423](https://cloud.githubusercontent.com/assets/7693239/13207292/cb0b24c0-d947-11e5-82d7-abedcd8a3ebd.png)
![qq 20160222093622](https://cloud.githubusercontent.com/assets/7693239/13207293/cb0bb188-d947-11e5-82e3-1247493ae011.png)

This can fix the modal at the bottom of screen. 
No matter what content in it. 
```
<Modal style={{
        right: 40,
        bottom: 0,
        left: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(58, 93, 15, 0.8)',
        overflow: 'hidden'
    }}>
...content here
</Modal>
```

It can do anything like using a `<View />` component.

**Comment by magicismight** [comment]
A `<Modal />` is a sibling element  to the root element of APP.
It is just something like this.
Root element is the one you registered by using `AppRegistry.registerComponent('xxx', Root)`.
```
<View style={{flex:1}}>
<Root></Root>
<Modal style={[{position: 'absolute'}, styles.yourCustomStyle]}>
</Modal>
</View>
```
