### ISSUE TITLE
can't find the modal

### ISSUE THREAD

**Issue by weiyang123** [magicismight/react-native-root-modal#14]
npm install成功之后，确定node_modals目录中有该模块
运行报错
Unable to resolve module `react-native/Libraries/EventEmitter/EventEmitter` from `/Users/weiyang/Documents/guahao/react-native-app/reactNativeApp/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js`: Module does not exist in the module map

react-native 版本 0.49.3

**Comment by magicismight** [comment]
Plz upgrade to 2.0.0
