### ISSUE TITLE
"Import before AppRegistry.registerComponent"

### ISSUE THREAD

**Issue by Noitidart** [magicismight/react-native-root-modal#19]
Does this still hold true? I tested it by importing it in a place before AppRegistery.registerComponent and it seems to work fine.

But if we do have to import it, as I dont use Modal in that file, is it ok we import it like this:

```
import { AppRegistry } from 'react-native'
import 'react-native-root-modal' // i added this, is this ok, instead of `import Modal from 'react-native-root-modal'`
import App from './App'

AppRegistry.registerComponent('trustedfamily', () => App)
```

**Comment by magicismight** [comment]
Just import it before `AppRegistry.registerComponent` would work, no need to use it in that file
